const myWeek = [
    {
        day:"Monday",
        activity:"study",
        category:"academic",
        hoursSpent:6,
        enjoyment:6,
        timeOfDay:"afternoon"
    },
    {
        day:"Tuesday",
        activity:"study",
        category:"academic",
        hoursSpent:6,
        enjoyment:7,
        timeOfDay:"afternoon"
    },
        {
        day:"Wednesday",
        activity:"shopping",
        category:"social",
        hoursSpent:4,
        enjoyment:5,
        timeOfDay:"morning"
    },
    {
        day:"Thursday",
        activity:"study",
        category:"academic",
        hoursSpent:5,
        enjoyment:6,
        timeOfDay:"afternoon"
    },
    {
        day:"Friday",
        activity:"reading",
        category:"personal",
        hoursSpent:3,
        enjoyment:9,
        timeOfDay:"evening"
    },
    {
        day:"Saturday",
        activity:"concert",
        category:"personal", 
        hoursSpent:4,
        enjoyment:10,
        timeOfDay:"afternoon"
    },
    {
        day:"Sunday",
        activity:"music lessons",
        category:"creative", 
        hoursSpent:2,
        enjoyment:7,
        timeOfDay:"morning"
    }
];